name: monomer
channels:
  - conda-forge
  - pytorch
dependencies:
  - python
  - numpy>=1.16
  - pytorch>0.4
  - pip
  - jupyterlab
  - pip:
    - torchvision==0.1.9
    - opencv-python
    - matplotlib
